### ISSUE TITLE
Muzi Li Code Review

### ISSUE THREAD

**Issue by Marlon666** [jiahaozh/EC601-Project#2]
# Read Me
From the code part, I can see you guys have achieved the database connection by using mysql, and an interface for users to log on as well as some python files(which is the core part) to achieve the your MVP: predict stock price from news story.

## Comment
I can really see a working prototype of what you guys have described in the sprint1 and 2, which is good. I think the next step of you should achieve more rather than using the API of Aylien to grab the news, to develop deeper potential of such tools and make it really helpful and useful in people's life.
### main page
The code is neat but maybe need to be more commented, I have downloaded it on my side and personally think it may be a little bit simple and lack some user friendly. I think you guys can definitely design it better or may be using the API such as Google or Twitter for users to log on.
### Algorithm
news.py is used for web scraping and text get, I can not run your code on my computer but I have looked through it. I think the error reason is due to missing files, please make sure you have uploaded all the file needed next time:)
plot1.py is what you use to plot the linear regression algorithm, I ran it on my computer and am able to see the result, I think next time with the data combined and more ameliorated function you can absolutely achieve the result as you want. At that time may be you can add a comparing with the real situation to the stock market so that your invention would be more convincing.

## Suggestion
Finally, just for suggestion, may be you can set more folders to hold different part of function , which is more clear and easier for you guys to work, and a readme file can help others to catch the point of your project easier. 

Nice job!
Muzi

**Comment by abhivora1** [comment]
Hey, Thanks for the review, we will look into these comments
