### ISSUE TITLE
Code Review - Bowen Song

### ISSUE THREAD

**Issue by Bowenislandsong** [jiahaozh/EC601-Project#3]
# Project Layout
The project presented on Github page has less attractiveness. A partitioned layout would present a much better view. The project should also work on the readme file for project introduction. Sectioning only by name of the  code files is less productive.
## Version Control
Project has minor version control over news.py. Project could use Github's native version control or setup archive folder for storing these data.
# WEB UI Testing
The webUI has very attractive coloring. Even though not all features are included yet, the implemented features are user-friendly. The webUI uses customized authentication, the database is although not presented in the project. It would also need to be hosted on a server. 
# Coding
The coding in python is less commendable since most of the code is commented out. The code relies heavily on hard coding. This is less reliable and the data set used for the code is not present in the solution or in any explanation. 
## Use of External Help
The project uses no external libraries. This is less disable since a lot of the work can be saved if the project uses already built functions for features such as login, user information storage, and news crawling. Since this project is heavily based on social media, usage APIs like twitter will save a lot of work. The core development should be focusing on recognizing and handling incoming data. The news-v2 tries to use API; unfortunately it is still under construction.
## WebUI Improvement Suggestion
For webUI, it would improve the result if bootstraps is used for formatting. It would create a more user appealing result.
# Coding Style
The layout of the code is not sectioned or well commented. A good practice would be listing the usage of the code, input and output parameters. Most importantly commenting on how to use each defined function would help fellow teammates to be more productive.

**Comment by abhivora1** [comment]
Hey, Thanks for the review, we will look into these comments
