### ISSUE TITLE
Code Review - Xiaoxi Chen

### ISSUE THREAD

**Issue by chenxiaoxi729** [jiahaozh/EC601-Project#4]
## **README.md**
It is good to have a brief but clear introduction to your project. 

 ## **Connector.php**
You achieved the function to save the users’ information to the MySQL Database. The code is clear and easy to understand. Did you put your work on the server? 

## **Code Formatting**
For those PHP coding part, most of the files have the clean and tidy format. However, the code formatting of register.html could be adjusted a little bit. The spaces in line14 could be eliminated. 

For the stylesheet.css, the position of brackets of the ‘body’ and ‘header’ should be the same and please take care of the alignments of your code. 

For the python code part, please also pay attention to the alignments. 

## **Architecture**
You did a great job in HTML, PHP,  and CSS, but I do think you need to add more comments on them as your WebUI becomes more and more complicated. 

Also, I tried to run your python code on my laptop, but there are some issues with your code so that I didn’t see all the result of your code. However, the output of the linearregression.py is really attractive, and the code is very comfortable to read. If you change the Chinese comments into English could be much better.

## **Suggestion to WebUI**
I highly recommend you to use some frameworks to adjust your format, and the color selection is a little bit simple. 

Plus, you can add some icons to your web pages to make them look fancy, I would recommend the "fontawesome", you can search it from google, it's really easy to use, and provides various vector-based pictures and all kinds of fonts.

**Comment by abhivora1** [comment]
Hey, Thanks for the review, we will look into these comments
