### ISSUE TITLE
Code Review --Xiaoxi Chen

### ISSUE THREAD

**Issue by chenxiaoxi729** [jiahaozh/EC601-Project#6]
## **Code Formatting**

I can see you made a great improvement on the formatting, but I still think you need to add more comments on your code, especially the machine learning algorithms. When the algorithm becomes more complicated, you need the comments to reminds you of every procedure you did before, and it is also very convenient for others to understand your code.

## **Architecture**

You changed your project GitHub architecture yesterday. The improved one is cleared and tidy. However, I recommend you to distinguish between the latest code and newest one so that we could know which you are using now and which you are not using anymore. 

## **WebUI**

You are still working on your website and I don’t see much difference from the last code review. You have already implemented the HTML part, and showed all basic functions of your project. If you want to make the website looks better, you could do more on the stylesheet.css. I noticed that you use the hard code, i.e. padding-top: 50px; , in your CSS code, which is ok for the body part, but when it comes to the “div” part, it is better to use the percentage rather than exact numbers, or when the users change the browser window size, your content might not change with their motions.

**Comment by abhivora1** [comment]
@chenxiaoxi729  Thanks, will make the ML code more reader friendly. 
You can visit the webpage now, and you'll see the changes made.
